Add automatic image support for various archs

diff --git a/Dockerfile.arm b/Dockerfile.arm
--- a/Dockerfile.arm
+++ b/Dockerfile.arm
@@ -9,7 +9,21 @@ RUN apk add --no-cache git
 
 # Copy & build
 ADD . /go/src/github.com/thomseddon/traefik-forward-auth/
-RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GO111MODULE=on go build -a -installsuffix nocgo -o /traefik-forward-auth github.com/thomseddon/traefik-forward-auth/cmd
+RUN set -ex; \
+	\
+ 	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+        armv[567])  Arch="arm"      ;; \
+        aarch64)    Arch='arm64'    ;; \
+        armhf)      Arch='arm'      ;; \
+		ppc64le)    Arch='ppc64le'  ;; \
+		s390x)      Arch='s390x'    ;; \
+		x86)        Arch='386'      ;; \
+		x86_64)     Arch='amd64'    ;; \
+ 		*) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
+ 	esac; \
+    \
+    CGO_ENABLED=0 GOOS=linux GOARCH=${Arch} GO111MODULE=on go build -a -installsuffix nocgo -o /traefik-forward-auth github.com/thomseddon/traefik-forward-auth/cmd
 
 # Copy into scratch container
 FROM scratch
